
export const ADD_TASK = "ADD_TASK";
export const REGISTER_USER = "REGISTER_USER";
export const ROOT_URL = "https://secure-escarpment-33875.herokuapp.com"
export const GET_PUBLIC_TASKS = "GET_PUBLIC_TASKS"
export const GET_PRIVATE_TASKS = "GET_PRIVATE_TASKS"
export const GET_GROUP_TASKS = "GET_GROUP_TASKS"
export const FETCH_USER = "FETCH_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_ALL_USER = "GET_ALL_USER"
export const CREATE_GROUP = "CREATE_GROUP"
export const GET_GROUP = "GET_GROUP"

export const LOCAL_STORAGE_USER_ID = "LOCAL_STORAGE_USERN_ID"
export const LOCAL_STORAGE_PRIMARY_COLOR = "LOCAL_STORAGE_PRIMARY_COLOR"
export const LOCAL_STORAGE_SECONDARY_COLOR = "LOCAL_STORAGE_SECONDARY_COLOR"

export const CHANGE_COLORS = "CHANGE_COLORS"
export const CHANGE_PRIMARY_COLOR = "CHANGE_PRIMARY_COLOR"
export const CHANGE_SECONDARY_COLOR = "CHANGE_SECONDARY_COLOR"
